### ISSUE TITLE
void-variable ac-complete-octave

### ISSUE THREAD

**Issue by badkey** [coldnew/ac-octave#11]
Hi,
using 
> ;; URL: https://github.com/coldnew/ac-octave
> ;; Version: 0.6

 I get

> Auto-Complete mode enabled in current buffer
> auto-complete error: (void-variable ac-complete-octave)

Did I miss something? Where is ac-complete-octave normally defined?

**Comment by coldnew** [comment]
@badkey Did you still has this problem ? I test this version today and there's no such error.

I'll test a clean emacs later.

**Comment by coldnew** [comment]
ref #5

**Comment by badkey** [comment]
If I create the variable manually it nicely works:
(defvar ac-complete-octave
  '((candidates . ac-octave-candidate)
    (document . ac-octave-documentation)
    (candidate-face . ac-octave-candidate-face)
    (selection-face . ac-octave-selection-face)
    (init . ac-octave-init)
    (requires . 0) (cache) (symbol . "f")))

So, my guess is that ac-define-source does not work correctly.

**Comment by eike-f** [comment]
Hi!
Has this been included in the package?

**Comment by eike-f** [comment]
Hi!
Has this been included in the package?

**Comment by coldnew** [comment]
@eike-f  I'm not sure. Do you still has this problem ?

I didn't use ac-octave recently, if #5 not work, please let me know.

**Comment by eike-f** [comment]
I'm using version 20170220.1728 and still experience this, but the fix of badkey helped. I still get an error at startup:
`Error loading autoloads: (void-function ac-define-source)`
If it's any help, I'm using spacemacs.
The definition of `ac-define-source` is like that in the thread you referenced.

**Comment by eike-f** [comment]
Now with this fix auto-completion works for built-in functions. But variable names are not completed. Do I have to change this variable then?

**Comment by coldnew** [comment]
mmm... I think the issue caused the `void-variable ac-complete-octave` is due to the wrong documentation.

This plugin was written in 2009, I'm not sure if the `auto-complete.el` api had changed or not.

The wrong documentation is:

```emacs-lisp
(defun ac-octave-mode-setup ()
  (setq ac-sources '(ac-complete-octave)))
```

Should be change to:

```emacs-lisp
(defun ac-octave-mode-setup ()
  (setq ac-sources '(ac-source-octave)))
```
The macro `ac-defined-source` generate variable `ac-source-octave` not `ac-complete-octave`, so that's why we have this error.

```emacs-lisp
(defmacro ac-define-source (name source)
  "Source definition macro. It defines a complete command also."
  (declare (indent 1))
  `(progn
     (defvar ,(intern (format "ac-source-%s" name)))
     ;; Use `setq' to reset ac-source-NAME every time
     ;; `ac-define-source' is called.  This is useful, for example
     ;; when evaluating `ac-define-source' using C-M-x (`eval-defun').
     (setq ,(intern (format "ac-source-%s" name)) ,source)
     (defun ,(intern (format "ac-complete-%s" name)) ()
       (interactive)
       (auto-complete '(,(intern (format "ac-source-%s" name)))))))
```

I'll update the `ac-ocateve` setup and documentation to make it more firendly.

**Comment by eike-f** [comment]
It works now, thank you!
