### ISSUE TITLE
There is a tag named master

### ISSUE THREAD

**Issue by tarsius** [coldnew/ac-octave#15]
This repository contains a **tag** named `master`. That conflicts with the branch by the same name and can cause all kinds of issues.

When you delete the tag you should make sure to not only delete it here on Github, but also in every check out. Otherwise you might very well end up "re-creating" it when you push the next time.

**Comment by coldnew** [comment]
Thank you, I didn't notice that :)

**Comment by tarsius** [comment]
You are welcome!
