### ISSUE TITLE
void variable ac-source-octave

### ISSUE THREAD

**Issue by stardiviner** [coldnew/ac-octave#5]
Just as the title.

I'm using ac version: latest github version.
And Emacs: 24.3.50.1

**Comment by badkey** [comment]
Same here ( 20150111.1708 (melpa)) with emacs 25.

**Comment by stardiviner** [comment]
```elisp
;;;###autoload
(ac-define-source octave
  '((candidates . ac-octave-candidate)
    (document . ac-octave-documentation)
    (candidate-face . ac-octave-candidate-face)
    (selection-face . ac-octave-selection-face)
    (init . ac-octave-init)
    (requires . 0)
    (cache)
    (symbol . "f")))
```
It generate auto-complete source `ac-complete-octave`.
So the README doc need to change.

**Comment by coldnew** [comment]
ok, thanks :)

**Comment by badkey** [comment]
ok, I start understanding: ac-define-source returns a function
ac-complete-octave (that returns nil). However, the octave hook expects a
variable ac-complete-octave, right?

2017-02-21 2:26 GMT+01:00 stardiviner <notifications@github.com>:
